### ISSUE TITLE
not 45 degrees sprite

### ISSUE THREAD

**Issue by floppa-coder** [Semastaraka/AdditionalVanillaUnit#2]
Why sprites have parts that not 45 degrees? This is wrong!

**Comment by Semastaraka** [comment]
Ср, 1 февр. 2023 г. в 21:51, floppa-coder ***@***.***>:

> Why sprites have parts that not 45 degrees? This is wrong!
>
As far as I know, unit sprites are not drawn at an angle of 45 degrees.
